### ISSUE TITLE
[discussion] game semantics

### ISSUE THREAD

**Issue by xieyuheng** [xieyuheng/cell-complex#4]
- type as game
- two players: `verifier` and `falsifier`
- object (including function) as winning strategy for `verifier`
- just like a card game
  - `falsifier` owns all the `record_t` game -- logic conjunction
  - `verifier` owns all the `union_t` game -- logic disjunction
  - function type is called `pi_t` (instead of `arrow_t`)
    - in `args` of `pi_t` switch the ownership of cards between `verifier` and `falsifier`
    - in `ret` of `pi_t` the ownership remain the same
- a player's choice is a path to the target position
  - choosing a choice means to resume a paused game
- use normal-play winning rule
  - normal-play is a rule of game,  
    which means the first player who used up his/her choices loss the game

**Comment by zaoqi** [comment]
function如何作爲winning strategy
loss the game意味着什麼

**Comment by xieyuheng** [comment]
@zaoqi 最近 tg 我上不了, 可以来 irc  #cicada-language

**Comment by xieyuheng** [comment]
"function 如何作为 winning strategy"

首先要看 `pi_t` 如何作为 game
`pi_t` 有两部分 args 和 ret, 在 args 中 verifier 和 falsifier 的 choice 要交换
如果 falsifier 在 args 中赢了 A, 那么在 ret 中, verifier 可以模仿 falsifier 赢 A 的策略, 来赢 ret 中出现的 A

**Comment by xieyuheng** [comment]
"loss the game 意味着什麼"

据我所知 game play 的过程没有类型系统的对应
```
| game semantics               | type system |
|------------------------------+-------------|
| game                         | type        |
| game play                    | [unknow]    |
| winning strategy of verifier | object      |
```

不过我想 game play 可以用来测试 semantics 的设计

**Comment by xieyuheng** [comment]
moved to another repo
