### ISSUE TITLE
[discussion] bake our own pie in typescript

### ISSUE THREAD

**Issue by xieyuheng** [xieyuheng/cell-complex#5]

**Comment by zaoqi** [comment]
?

**Comment by xieyuheng** [comment]
这是为之后讨论 pie 的实现而开的 issue

**Comment by xieyuheng** [comment]
这个论文讲的是 pie 的实现技术 :: Normalization by Evaluation: Dependent Types and Impredicativity, by Andreas Abel

**Comment by xieyuheng** [comment]
还有这个 :: http://davidchristiansen.dk/tutorials/nbe

**Comment by xieyuheng** [comment]
好像 minitt 用的也是这个技术

**Comment by xieyuheng** [comment]
我强烈推荐 Normalization by Evaluation: Dependent Types and Impredicativity, by Andreas Abel
他用的语言比较晦涩, 远远不如 little book, 不过当代的 "学术论文" 都是这样.
能解码这些晦涩的语言也挺重要的.

这个比较适合有连续四个小时的时间的时候来阅读,
他术语上有写的不明白的地方, 你可以记录下来和我讨论.

**Comment by zaoqi** [comment]
Normalization by Evaluation: Dependent Types and Impredicativity, by Andreas Abel何处下载

**Comment by xieyuheng** [comment]
paper :: http://www2.tcs.ifi.lmu.de/~abel/habil.pdf
talk :: http://www.cse.chalmers.se/~abela/talkHabil2013.pdf

**Comment by xieyuheng** [comment]
我没看懂第 11 页的 NbE algorithm,
↑S->T 这行没看懂.

我感觉如果一个程序员把代码写成了这样, 那应该是不讲职业道德的 ...
写出了 APL 式的代码, 然后在后面注释说, "代码是错的, 因为我省略了一些重要参数" ...

我所尝试的实现在这里 :: https://github.com/xieyuheng/cicada/blob/master/src/nbe/simple.ts#L488
他可能假设了 在 meta language 里 使用 function 来表示 object language 里的 function.
他所描述的算法, 看来不是能照着实现的, 而必须先理解然后自己为自己的实现重新设计算法.

**Comment by xieyuheng** [comment]
他所说的 Variable Handling 里生成 fresh var 的难点, 用 uuid 生成就可以了, 
也就是类似 gensym

**Comment by xieyuheng** [comment]
paper 里不明确的地方, 应该可以用这个教程 来补充 :: http://davidchristiansen.dk/tutorials/nbe
教程起码是真的 可以跑的 有测试的 代码

**Comment by xieyuheng** [comment]
目的是写一个 Definitional Equality 的 checker, 
也可以想一想 normalization by evaluation 之外的方法.

**Comment by zaoqi** [comment]
> paper :: http://www2.tcs.ifi.lmu.de/~abel/habil.pdf
> talk :: http://www.cse.chalmers.se/~abela/talkHabil2013.pdf

我暂时无法找到足够的时间来看

**Comment by xieyuheng** [comment]
http://davidchristiansen.dk/tutorials/nbe/
我尝试一下在 ts 里跟着实现这个，这个不需要连续的时间就能看。

**Comment by xieyuheng** [comment]
你随时有时间了再看就好

**Comment by xieyuheng** [comment]
move to https://github.com/xieyuheng/tartlet
